# -*- coding: utf-8 -*-
"""
core/audio_processor.py
=======================

把一個目錄下的 ``*.mp3`` 批次轉成 tiptoi 點讀筆可吃的 OGG，並產生
對應的 ``tttool`` YAML / 組裝出 ``.gme`` 檔。

公開 API
--------

* :class:`ConvertResult`  - dataclass，紀錄一次轉檔的結果
* :func:`convert_directory(...)` - 一站式 (掃描 → 轉檔 → 寫 YAML → assemble)
* :func:`convert_one(...)`       - 單檔轉檔
* :func:`write_yaml(...)`        - 只寫 YAML
* :func:`run_tttool_assemble(...)` - 只跑 tttool assemble

設計原則
--------

1. **純函式**：不打印任何東西到 stdout；想要 log 請傳入 ``logger`` 或自行包。
2. **相對路徑**：回傳值都是 :class:`pathlib.Path`；呼叫端決定要不要 ``resolve()``。
3. **單向依賴**：只 import ``utils`` 與標準函式庫；不需要 reportlab / Pillow。
"""

from __future__ import annotations

import logging
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Tuple

from .utils import (
    AUDIO_CHANNELS,
    AUDIO_CODEC,
    AUDIO_QUALITY_DEFAULT,
    AUDIO_SAMPLE_RATE,
    ensure_dir,
    find_ffmpeg,
    find_tttool,
    humanize_size,
)

log = logging.getLogger(__name__)


# =====================================================================
# Dataclasses
# =====================================================================


@dataclass
class FileResult:
    """單檔轉檔的結果。"""

    src: Path
    dst: Path
    oid: int
    ok: bool
    message: str
    elapsed_s: float = 0.0


@dataclass
class ConvertResult:
    """:func:`convert_directory` 的彙整結果。"""

    files: List[FileResult] = field(default_factory=list)
    yaml_path: Optional[Path] = None
    gme_path: Optional[Path] = None
    assemble_log: str = ""
    assemble_ok: Optional[bool] = None  # None = 沒跑 assemble

    @property
    def successes(self) -> List[FileResult]:
        return [f for f in self.files if f.ok]

    @property
    def failures(self) -> List[FileResult]:
        return [f for f in self.files if not f.ok]

    @property
    def mappings(self) -> List[Tuple[int, str]]:
        """成功轉檔對應的 (oid, audio_name) — audio_name = OID 字串。"""
        return [(f.oid, str(f.oid)) for f in self.successes]


# =====================================================================
# 轉檔
# =====================================================================


def convert_one(
    src: Path,
    dst: Path,
    *,
    ffmpeg: Optional[str] = None,
    overwrite: bool = True,
    quality: int = AUDIO_QUALITY_DEFAULT,
    sample_rate: int = AUDIO_SAMPLE_RATE,
    channels: int = AUDIO_CHANNELS,
    codec: str = AUDIO_CODEC,
) -> Tuple[bool, str, float]:
    """
    把單一個 mp3 (或任何 ffmpeg 認得的格式) 轉成 ogg vorbis。

    回傳 ``(ok, message, elapsed_s)``。``ok=False`` 時 ``message`` 為錯誤摘要。
    """
    if ffmpeg is None:
        ffmpeg = find_ffmpeg()
    if ffmpeg is None:
        return False, "ffmpeg not found in PATH", 0.0

    if dst.exists() and not overwrite:
        return True, f"existing kept ({humanize_size(dst.stat().st_size)})", 0.0

    ensure_dir(dst.parent)

    cmd = [
        ffmpeg,
        "-loglevel", "error",
        "-y",
        "-i", str(src),
        "-vn",                      # 丟封面 / 影像
        "-map_metadata", "-1",      # 丟標籤，輸出乾淨檔
        "-ac", str(channels),
        "-ar", str(sample_rate),
        "-c:a", codec,
        "-q:a", str(quality),
        str(dst),
    ]
    t0 = time.monotonic()
    result = subprocess.run(cmd, capture_output=True, text=True)
    dt = time.monotonic() - t0

    if result.returncode != 0:
        return False, f"ffmpeg failed: {result.stderr.strip()[:200]}", dt
    if not dst.exists() or dst.stat().st_size == 0:
        return False, "ffmpeg returned 0 but output is empty", dt

    sz = dst.stat().st_size
    return True, f"{humanize_size(sz)} in {dt:.2f}s", dt


# =====================================================================
# YAML
# =====================================================================


def write_yaml(
    yaml_path: Path,
    product_id: int,
    mappings: Sequence[Tuple[int, str]],
    *,
    src_summary: str = "",
    comment: str = "tiptoi test pack (auto-built)",
    media_path: str = "./%s.ogg",
) -> Path:
    """
    寫出 ``tttool`` 可吃的 YAML：

    .. code-block:: yaml

        product-id: 999
        comment: tiptoi test pack (auto-built)
        media-path: ./%s.ogg
        scripts:
          1000: [P(1000)]
          1001: [P(1001)]
          ...

    *mappings* = ``[(oid, audio_name), ...]``。``audio_name`` 會：

    * 被插進 ``P(<audio_name>)`` 指令
    * 透過 ``media-path`` 的 ``%s`` 替換成檔名

    回傳 ``yaml_path``。
    """
    if not mappings:
        raise ValueError("mappings 不可為空")

    ensure_dir(yaml_path.parent)
    first, last = mappings[0][0], mappings[-1][0]
    lines: List[str] = [
        "# Auto-generated by tiptoi_toolbox.core.audio_processor",
    ]
    if src_summary:
        lines.append(f"# Source: {src_summary}")
    lines += [
        f"# {len(mappings)} entries, OID {first}..{last}",
        "",
        f"product-id: {product_id}",
        f"comment: {comment}",
        "",
        "# OGG 檔放在這個 YAML 同目錄；P(<name>) 透過 %s 替換為檔名",
        f"media-path: {media_path}",
        "",
        "scripts:",
    ]
    for oid, name in mappings:
        lines.append(f"  {oid}: [P({name})]")
    yaml_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return yaml_path


# =====================================================================
# Assemble (tttool)
# =====================================================================


def run_tttool_assemble(
    yaml_path: Path,
    gme_path: Optional[Path] = None,
    *,
    tttool: Optional[str] = None,
) -> Tuple[bool, str, Path]:
    """
    呼叫 ``tttool assemble``。為了讓 YAML 內的 ``media-path: ./%s.ogg`` 能解析，
    cwd 會切到 ``yaml_path.parent``，所以 ``yaml_path`` / ``gme_path`` 都建議放
    OGG 同目錄 (一般就是 ``audio/`` 目錄)。

    回傳 ``(ok, combined_log, gme_path)``。
    """
    if tttool is None:
        tttool = find_tttool()
    if tttool is None:
        return False, "tttool not found in PATH", gme_path or yaml_path.with_suffix(".gme")

    if gme_path is None:
        gme_path = yaml_path.with_suffix(".gme")

    cmd = [tttool, "assemble", yaml_path.name, gme_path.name]
    result = subprocess.run(
        cmd,
        cwd=str(yaml_path.parent),
        capture_output=True,
        text=True,
    )
    out = (result.stdout or "") + (result.stderr or "")
    ok = result.returncode == 0 and gme_path.exists() and gme_path.stat().st_size > 0
    return ok, out, gme_path


# =====================================================================
# 一站式：scan → convert → yaml → assemble
# =====================================================================


def scan_mp3(src_dir: Path) -> List[Path]:
    """列出 ``src_dir`` 下所有 ``*.mp3``，按檔名 (case-insensitive) 排序。"""
    if not src_dir.exists() or not src_dir.is_dir():
        return []
    return sorted(
        (p for p in src_dir.iterdir()
         if p.is_file() and p.suffix.lower() == ".mp3"),
        key=lambda p: p.name.lower(),
    )


def convert_directory(
    src_dir: Path,
    out_dir: Optional[Path] = None,
    *,
    start_oid: int = 1000,
    product_id: int = 999,
    yaml_path: Optional[Path] = None,
    gme_path: Optional[Path] = None,
    overwrite: bool = True,
    quality: int = AUDIO_QUALITY_DEFAULT,
    assemble: bool = True,
    on_progress=None,
) -> ConvertResult:
    """
    主流程：

    1. 掃 ``src_dir/*.mp3``，按檔名排序
    2. 從 ``start_oid`` 開始遞增，逐一轉成 ``out_dir/<OID>.ogg``
    3. 寫 YAML 至 ``yaml_path`` (預設 ``out_dir/test.yaml``)
    4. 若 ``assemble=True`` 且找得到 tttool，跑 ``tttool assemble``

    路徑說明
    ~~~~~~~~

    * ``out_dir`` 預設 = ``src_dir.parent`` (即 mp3 在 ``audio/src/``，
      ogg 寫到 ``audio/``)
    * ``yaml_path`` / ``gme_path`` 預設都在 ``out_dir`` 內
    * 全部都用 :class:`Path` 物件，不會做 ``resolve()``，保留呼叫端傳入的形式

    回呼
    ~~~~

    ``on_progress(idx, total, file_result)`` 會在每個檔案處理完後被呼叫
    (idx 從 1 開始)。給 CLI 拿來印進度用。

    回傳 :class:`ConvertResult`。
    """
    if out_dir is None:
        out_dir = src_dir.parent
    if yaml_path is None:
        yaml_path = out_dir / "test.yaml"
    if gme_path is None:
        gme_path = yaml_path.with_suffix(".gme")

    ensure_dir(out_dir)
    result = ConvertResult()

    ffmpeg = find_ffmpeg()
    if ffmpeg is None:
        # 全部標記失敗、但仍回傳一個有資訊的結果
        for src in scan_mp3(src_dir):
            result.files.append(FileResult(
                src=src, dst=out_dir / "(none)", oid=-1,
                ok=False, message="ffmpeg not found in PATH",
            ))
        return result

    mp3_files = scan_mp3(src_dir)
    total = len(mp3_files)

    for i, mp3 in enumerate(mp3_files):
        oid = start_oid + i
        ogg_path = out_dir / f"{oid}.ogg"
        ok, msg, dt = convert_one(
            mp3, ogg_path,
            ffmpeg=ffmpeg, overwrite=overwrite, quality=quality,
        )
        fr = FileResult(src=mp3, dst=ogg_path, oid=oid,
                        ok=ok, message=msg, elapsed_s=dt)
        result.files.append(fr)
        if on_progress is not None:
            try:
                on_progress(i + 1, total, fr)
            except Exception:  # noqa: BLE001 — progress 失敗不影響主流程
                log.exception("on_progress callback raised")

    # YAML
    if result.successes:
        write_yaml(
            yaml_path,
            product_id=product_id,
            mappings=result.mappings,
            src_summary=f"{src_dir} ({len(mp3_files)} mp3)",
        )
        result.yaml_path = yaml_path

    # Assemble
    if assemble and result.successes:
        ok, out, gme_path_actual = run_tttool_assemble(yaml_path, gme_path)
        result.assemble_ok = ok
        result.assemble_log = out
        if ok:
            result.gme_path = gme_path_actual

    return result


__all__ = [
    "FileResult",
    "ConvertResult",
    "convert_one",
    "convert_directory",
    "scan_mp3",
    "write_yaml",
    "run_tttool_assemble",
]
